function [fitresult, gof] = createFit(SeedSizesInverse, HexStressOutside)
%CREATEFIT(SEEDSIZESINVERSE,HEXSTRESSOUTSIDE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: SeedSizesInverse
%      Y Output: HexStressOutside
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Dec-2022 14:57:20


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( SeedSizesInverse, HexStressOutside );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.99999;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'HexStressOutside vs. SeedSizesInverse', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'SeedSizesInverse', 'Interpreter', 'none' );
ylabel( 'HexStressOutside', 'Interpreter', 'none' );
grid on

% RMSE = 4.6604


